"""empty message

Revision ID: 3a55ac2db97b
Revises: 0747543e3e7e
Create Date: 2024-07-25 09:19:11.076502

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a55ac2db97b"
down_revision: Union[str, None] = "0747543e3e7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("_password", sa.String(length=128), nullable=True))
    op.drop_column("user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "password", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("user", "_password")
    # ### end Alembic commands ###
